language: go
sudo: false
install: make deps bats
before_deploy: make dist
deploy:
  provider: releases
  api_key:
    secure: hb586to31wbpn//4UrnMhf7rVhcSu4Iz7z3tLNe4PbBzZsm3y7lZ1RnpkpcxzCV1hgD0rcVGYi77RZCJ5zGyTtMJEq3fOJlA7OPvvSx6TzD4hCznoyy3YiYj5OQsulcKSnAuuW7D3rHNoYJPDOKh44cO5FkOvFb+YJXIhyxGTBY=
  file: "dist/git_substitute*.tar.gz"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
