language: c
sudo: required
addons:
  apt:
    packages:
      - autoconf 
      - libtool 
      - ncurses-dev 
      - g++ 
      - dblatex 
      - docbook-xsl 
      - docbook-utils
      - libgmp-dev
      - libgmp10
      - libncurses5-dev
      - libtinfo5
      - llvm
services:
  - docker
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install: make get-deps
script: make dist
before_deploy: make dist
deploy:
  provider: releases
  api_key:
    secure: hb586to31wbpn//4UrnMhf7rVhcSu4Iz7z3tLNe4PbBzZsm3y7lZ1RnpkpcxzCV1hgD0rcVGYi77RZCJ5zGyTtMJEq3fOJlA7OPvvSx6TzD4hCznoyy3YiYj5OQsulcKSnAuuW7D3rHNoYJPDOKh44cO5FkOvFb+YJXIhyxGTBY=
  file:
    - "dist/git_substitute_linux_amd64.tar.gz"
    - "dist/git_substitute_linux_386.tar.gz"
    - "dist/git_substitute_darwin_amd64.tar.gz"
    - "dist/git_substitute_darwin_386.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
